spring:
  kafka:
    consumer:
      bootstrap-servers: 35.219.146.212:9092
    topic:
      name: notify-driver
    group:
      id: notify-driver-group
    containerFactory:
      name: kafkaListenerContainerFactory