spring:
  data:
    mongodb:
      uri: mongodb+srv://campushareAdmin:campusharePassword@clustercampushare.qhbomhf.mongodb.net/?retryWrites=true&w=majority
      database: NotificationDB
  kafka:
    consumer:
      bootstrap-servers: 35.219.146.212:9092
    topic:
      name: notify-driver
    group:
      id: notify-driver-group
    containerFactory:
      name: kafkaListenerContainerFactory